export const CARD_MOTION_SIZES = {
  genericEntryOffsetY: 20,
  genericLeaveOffsetY: 12,
  genericLeaveBlur: 2,
  glowEntryOffsetY: -8,
  glowEntryScale: 0.7,
  glowEntrySkewX: 4,
  glowEntrySkewY: 8,
  glowEntryRadiusFrom: 24,
  glowEntryRadiusTo: 12,
  glowMaxSkewX: 8,
  glowMaxSkewY: 12,
  hoverLiftY: -4,
  glowShadowInsetWidth: 1,
  glowShadowOffsetY: 14,
  glowShadowBlur: 40,
  transformPerspective: 1000,
  contentBlurFrom: 8,
  contentOffsetY: 8,
} as const;
