// GENERATED by scripts/gen-css-showcase-data.mjs — do not hand-edit.
// Source of truth: `git diff master` (changes) + Storybook index (storyId).

export type CssUpdateRecord = {
  title: string;
  path: string;
  changes: string[];
  storyId?: string;
};

export const cssUpdateRecords: CssUpdateRecord[] = [
  {
    "title": "root-components",
    "path": "src/app-loaders/load-component/root-components.scss",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `box-shadow: 0 8px 16px rgba(4, 5, 6, 0.1);` to `box-shadow: 0 8px 16px rgba(var(--fn-shadow-rgb), 0.1);`."
    ]
  },
  {
    "title": "AIAssistantPanel",
    "path": "src/core/AIAssistant/AIAssistentPanel/AIAssistantPanel.module.scss",
    "storyId": "aiassistant-aiassistant--default",
    "changes": [
      "Changed `background: var(--functional-bg-surface, #fff);` to `background: var(--fn-bg-surface);`.",
      "Changed `border: 1px solid var(--ai, rgba(131, 119, 228, 0.25));` to `border: 1px solid var(--ai, rgba(var(--a1300-rgb), 0.25));`.",
      "Changed `box-shadow: 0px 16px 64px 0px rgba(4, 5, 6, 0.08), 0px 12px 20px 0px rgba(4, 5, 6, 0.05),` to `box-shadow: 0px 16px 64px 0px rgba(var(--fn-shadow-rgb), 0.08), 0px 12px 20px 0px rgba(var(--fn-shadow-rgb), 0.05),`.",
      "Changed `0px 6px 8px 0px rgba(4, 5, 6, 0.03);` to `0px 6px 8px 0px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `background: var(--functional-bg-surface-hover, #f5f5f5);` to `background: var(--fn-bg-var);`.",
      "Changed `background: var(--functional-bg-surface, #fff);` to `background: var(--fn-bg-surface);`.",
      "Changed `box-shadow: 0px 16px 64px 0px rgba(4, 5, 6, 0.08), 0px 12px 20px 0px rgba(4, 5, 6, 0.05),` to `box-shadow: 0px 16px 64px 0px rgba(var(--fn-shadow-rgb), 0.08), 0px 12px 20px 0px rgba(var(--fn-shadow-rgb), 0.05),`.",
      "Changed `0px 6px 8px 0px rgba(4, 5, 6, 0.03);` to `0px 6px 8px 0px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `fill: var(--acc-01500, #3c28cc);` to `fill: var(--a1500);`."
    ]
  },
  {
    "title": "Accordion",
    "path": "src/core/Accordion/Accordion.scss",
    "storyId": "accordion-accordion--default",
    "changes": [
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`."
    ]
  },
  {
    "title": "ActionBar",
    "path": "src/core/ActionBar/ActionBar.module.scss",
    "storyId": "actionbar-actionbar--default",
    "changes": [
      "Changed `background: white;` to `background: var(--fn-bg);`.",
      "Changed `box-shadow: 0px -8px 24px rgba(4, 5, 6, 0.08), 0px -4px 8px rgba(4, 5, 6, 0.05), 0px -2px 2px rgba(4, 5, 6, 0.03);` to `box-shadow: 0px -8px 24px rgba(var(--fn-shadow-rgb), 0.08), 0px -4px 8px rgba(var(--fn-shadow-rgb), 0.05), 0px -2px 2px rgba(var(--fn-shadow-rgb), 0.03);`."
    ]
  },
  {
    "title": "ActionButton",
    "path": "src/core/ActionButton/ActionButton.module.scss",
    "storyId": "actionbutton-actionbutton--default",
    "changes": [
      "Changed `background: var(--n000) !important;` to `background: var(--fn-bg) !important;`.",
      "Changed `background: var(--p100) !important;` to `background: var(--i100) !important;`.",
      "Changed `color: var(--p500) !important;` to `color: var(--fn-fg-cta) !important;`."
    ]
  },
  {
    "title": "ActionCard",
    "path": "src/core/ActionCard/ActionCard.module.scss",
    "storyId": "actioncard-actioncard--default",
    "changes": [
      "Changed `background-color: rgba(var(--n000-rgb), 0.6);` to `background-color: rgba(var(--fn-bg-rgb), 0.6);`."
    ]
  },
  {
    "title": "ActionCardAction",
    "path": "src/core/ActionCard/ActionCardActions/ActionCardAction/ActionCardAction.module.scss",
    "storyId": "actioncard-actioncardactions-actioncardaction-actioncardaction--basic",
    "changes": [
      "Changed `$loader-color: var(--p100);` to `$loader-color: var(--i100);`.",
      "Changed `$loader-color2: var(--p400);` to `$loader-color2: var(--i400);`.",
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`."
    ]
  },
  {
    "title": "ActionCardActions",
    "path": "src/core/ActionCard/ActionCardActions/ActionCardActions.module.scss",
    "storyId": "actioncard-actioncard--default",
    "changes": [
      "Changed `box-shadow: 0 1px 0 0 #E5E9F0 inset;` to `box-shadow: 0 1px 0 0 var(--fn-divider-gl) inset;`."
    ]
  },
  {
    "title": "AutocompleteWithAnchor",
    "path": "src/core/AutocompleteWithAnchor/AutocompleteWithAnchor.module.scss",
    "storyId": "autocompletewithanchor-autocompletewithanchor--with-input",
    "changes": [
      "Changed `background-color: white;` to `background-color: var(--fn-bg-surface);`.",
      "Changed `box-shadow: 0px 12px 40px rgba(4, 5, 6, 0.08), 0px 8px 14px rgba(4, 5, 6, 0.05), 0px 4px 4px rgba(4, 5, 6, 0.03);` to `box-shadow: 0px 12px 40px rgba(var(--fn-shadow-rgb), 0.08), 0px 8px 14px rgba(var(--fn-shadow-rgb), 0.05), 0px 4px 4px rgba(var(--fn-shadow-rgb), 0.03);`."
    ]
  },
  {
    "title": "Avatar",
    "path": "src/core/Avatar/Avatar.module.scss",
    "storyId": "avatar-avatar--default",
    "changes": [
      "Changed `border: 1px solid var(--n100);` to `border: 1px solid var(--fn-brd-gl);`.",
      "Changed `border-color: var(--p500);` to `border-color: var(--fn-fg-cta);`.",
      "Changed `border-color: var(--n100) !important;` to `border-color: var(--fn-brd-gl) !important;`.",
      "Changed `background: #ff1f69; /* todo: replace with variable from semanticColors/nav/side/notif/bg after sideNav is merged into A23-98 */` to `background: var(--a3500); /* todo: replace with variable from semanticColors/nav/side/notif/bg after sideNav is merged into A23-98 */`."
    ]
  },
  {
    "title": "AvatarStack",
    "path": "src/core/AvatarStack/AvatarStack.module.scss",
    "storyId": "avatarstack-avatarstack--default",
    "changes": [
      "Changed `background: var(--n500);` to `background: var(--fn-bg-hov-n-gl);`."
    ]
  },
  {
    "title": "BenchmarkGauge",
    "path": "src/core/BenchmarkGauge/BenchmarkGauge.module.scss",
    "storyId": "benchmarkgauge-stories-benchmarkgauge--horizontal",
    "changes": [
      "Changed `background: var(--legend-item-bg, #fff);` to `background: var(--legend-item-bg, var(--fn-bg));`.",
      "Changed `background: rgba(var(--n900-rgb), 0.2);` to `background: rgba(var(--fn-shadow-rgb), 0.8);`."
    ]
  },
  {
    "title": "BenchmarkGaugePin",
    "path": "src/core/BenchmarkGauge/BenchmarkGaugeMarker/BenchmarkGaugePin/BenchmarkGaugePin.module.scss",
    "storyId": "benchmarkgauge-stories-benchmarkgauge--horizontal",
    "changes": [
      "Changed `border: $x0_5 solid var(--n000);` to `border: $x0_5 solid var(--fn-bg);`.",
      "Changed `border: $x0_25 + $x0_125 solid var(--n000);` to `border: $x0_25 + $x0_125 solid var(--fn-bg);`."
    ]
  },
  {
    "title": "Button",
    "path": "src/core/Button/Button.module.scss",
    "storyId": "button-button--button-type-primary",
    "changes": [
      "Changed `background-color: #B6C1D3;` to `background-color: var(--fn-bg-hov-n-gl);`."
    ]
  },
  {
    "title": "CardMotion",
    "path": "src/core/CardMotion/CardMotion.module.scss",
    "storyId": "cardmotion-cardmotion--default",
    "changes": [
      "Changed `background: rgba(var(--n100-rgb), var(--card-motion-glow-alpha-from));` to `background: rgba(var(--fn-bg-rgb), var(--card-motion-glow-alpha-from));`.",
      "Changed `inset 0 0 0 var(--card-motion-shadow-inset-width) rgba(var(--n000-rgb), calc(0.95 * var(--card-motion-glow-alpha-from))),` to `inset 0 0 0 var(--card-motion-shadow-inset-width) rgba(var(--fn-bg-rgb), calc(0.95 * var(--card-motion-glow-alpha-from))),`.",
      "Changed `0 var(--card-motion-shadow-offset-y) var(--card-motion-shadow-blur) rgba(var(--n000-rgb), calc(0.55 * var(--card-motion-glow-alpha-from)));` to `0 var(--card-motion-shadow-offset-y) var(--card-motion-shadow-blur) rgba(var(--fn-shadow-rgb), calc(0.55 * var(--card-motion-glow-alpha-from)));`.",
      "Changed `inset 0 0 0 var(--card-motion-shadow-inset-width) rgba(var(--n000-rgb), 0),` to `inset 0 0 0 var(--card-motion-shadow-inset-width) rgba(var(--fn-bg-rgb), 0),`.",
      "Changed `0 var(--card-motion-shadow-offset-y) var(--card-motion-shadow-blur) rgba(var(--n000-rgb), 0);` to `0 var(--card-motion-shadow-offset-y) var(--card-motion-shadow-blur) rgba(var(--fn-shadow-rgb), 0);`."
    ]
  },
  {
    "title": "CardMotionStories",
    "path": "src/core/CardMotion/stories/CardMotionStories.module.scss",
    "storyId": "cardmotion-cardmotion--default",
    "changes": [
      "Changed `border: $x0_125 solid var(--n200);` to `border: $x0_125 solid var(--fn-brd-gl);`.",
      "Changed `color: var(--n900);` to `color: var(--fn-fg);`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `background: var(--n100);` to `background: var(--fn-bg-var);`.",
      "Changed `border-color: var(--p100);` to `border-color: var(--i100);`.",
      "Changed `background: var(--p100);` to `background: var(--i100);`.",
      "Changed `border-color: var(--p500);` to `border-color: var(--i400);`.",
      "Changed `border-color: var(--n200);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `border-color: var(--n200);` to `border-color: var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "BarChart",
    "path": "src/core/Charts/BarChart/BarChart.scss",
    "storyId": "charts-barchart-barchart--default",
    "changes": [
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `background: var(--n800);` to `background: var(--fn-bg-dark);`.",
      "Changed `box-shadow: 0 8px 24px rgba(4, 5, 6, 0.08), 0 4px 8px rgba(4, 5, 6, 0.05), 0 2px 2px rgba(4, 5, 6, 0.03);` to `box-shadow: 0 8px 24px rgba(var(--fn-shadow-rgb), 0.08), 0 4px 8px rgba(var(--fn-shadow-rgb), 0.05), 0 2px 2px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `color: var(--n900);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`."
    ]
  },
  {
    "title": "HSBChart",
    "path": "src/core/Charts/HSBChart/HSBChart.scss",
    "storyId": "charts-hsbchart-hsbchart--default",
    "changes": [
      "Changed `background: var(--n800);` to `background: var(--fn-bg-dark);`.",
      "Changed `box-shadow: 0 8px 24px rgba(4, 5, 6, 0.08), 0 4px 8px rgba(4, 5, 6, 0.05), 0 2px 2px rgba(4, 5, 6, 0.03);` to `box-shadow: 0 8px 24px rgba(var(--fn-shadow-rgb), 0.08), 0 4px 8px rgba(var(--fn-shadow-rgb), 0.05), 0 2px 2px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`."
    ]
  },
  {
    "title": "LineChart",
    "path": "src/core/Charts/LineChart/LineChart.scss",
    "storyId": "charts-linechart-linechart--zero-day-one-point-chart",
    "changes": [
      "Changed `stroke: #2A3546; //todo: replace this with --fn-fg variable` to `stroke: var(--fn-fg); //todo: replace this with --fn-fg variable`.",
      "Changed `stroke: rgba(4, 5, 6, 0.2); // todo: replace with opacity/n900/20` to `stroke: rgba(var(--fn-shadow-rgb), 0.2); // todo: replace with opacity/n900/20`.",
      "Changed `fill: var(--n600);` to `fill: var(--fn-fg-light);`.",
      "Changed `color: var(--n700) !important;` to `color: var(--fn-fg) !important;`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `background: #171D26;` to `background: var(--fn-bg-dark);`.",
      "Changed `box-shadow: 0 8px 24px rgba(4, 5, 6, 0.08), 0 4px 8px rgba(4, 5, 6, 0.05), 0 2px 2px rgba(4, 5, 6, 0.03);` to `box-shadow: 0 8px 24px rgba(var(--fn-shadow-rgb), 0.08), 0 4px 8px rgba(var(--fn-shadow-rgb), 0.05), 0 2px 2px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`."
    ]
  },
  {
    "title": "CheckBox",
    "path": "src/core/CheckBox/CheckBox.scss",
    "storyId": "checkbox-stories-checkbox--default",
    "changes": [
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `border: 2px solid var(--p500);` to `border: 2px solid var(--fn-bg-cta);`.",
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `border: 2px solid var(--p300);` to `border: 2px solid var(--fn-bg-cta);`.",
      "Changed `border: 2px solid var(--p500);` to `border: 2px solid var(--fn-bg-cta);`.",
      "Changed `background: var(--p500);` to `background: var(--fn-bg-cta);`.",
      "Changed `border: 2px solid var(--p500);` to `border: 2px solid var(--fn-bg-cta);`.",
      "Changed `background: var(--p600);` to `background: var(--fn-bg-cta-hov);`.",
      "Changed `border: 2px solid var(--p600);` to `border: 2px solid var(--fn-bg-cta-hov);`.",
      "Changed `background: var(--p600);` to `background: var(--fn-bg-cta-hov);`.",
      "Changed `border: 2px solid var(--p600);` to `border: 2px solid var(--fn-bg-cta-hov);`.",
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "CircularGauge",
    "path": "src/core/CircularGauge/CircularGauge.module.scss",
    "changes": [
      "Added `.container {`.",
      "Added `position: relative;`.",
      "Added `display: inline-flex;`.",
      "Added `align-items: center;`.",
      "Added `justify-content: center;`.",
      "Added `.svg {`.",
      "Added `display: block;`.",
      "Added `.value-arc {`.",
      "Added `transition: stroke-dashoffset 0.6s cubic-bezier(0.23, 1, 0.32, 1), stroke 0.25s ease;`.",
      "Added `.center {`.",
      "Added `position: absolute;`.",
      "Added `inset: 0;`.",
      "Added `display: flex;`.",
      "Added `align-items: center;`.",
      "Added `justify-content: center;`.",
      "Added `text-align: center;`."
    ]
  },
  {
    "title": "ClipboardText",
    "path": "src/core/ClipboardText/ClipboardText.module.scss",
    "storyId": "clipboardtext-clipboardtext--default",
    "changes": [
      "Changed `border-bottom: 1px solid var(--functional-divider-gl, #e5e9f0);` to `border-bottom: 1px solid var(--fn-divider-gl);`.",
      "Changed `border: 1px solid var(--functional-divider-gl, #e5e9f0);` to `border: 1px solid var(--fn-divider-gl);`.",
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `border: 1px solid var(--n200);` to `border: 1px solid var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "ColorPicker",
    "path": "src/core/ColorPicker/ColorPicker.module.scss",
    "storyId": "colorpicker-colorpicker--default",
    "changes": [
      "Changed `border: 1px solid #ccc;` to `border: 1px solid var(--fn-brd-gl);`.",
      "Changed `border: 1px solid #ccc;` to `border: 1px solid var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "Cropper",
    "path": "src/core/Cropper/Cropper.scss",
    "storyId": "cropper-cropper--default",
    "changes": [
      "Changed `background: rgba(255, 255, 255, 0.1);` to `background: rgba(var(--fn-bg-rgb), 0.1);`.",
      "Changed `border-right: var(--rc-cropper-border-width, 0) dashed var(--n000);` to `border-right: var(--rc-cropper-border-width, 0) dashed var(--fn-fg-on-dark);`.",
      "Changed `background: rgba(255, 255, 255, 0.1);` to `background: rgba(var(--fn-bg-rgb), 0.1);`.",
      "Changed `border-left:  var(--rc-cropper-border-width, 0) dashed var(--n000);` to `border-left:  var(--rc-cropper-border-width, 0) dashed var(--fn-fg-on-dark);`.",
      "Changed `border: var(--n100) 2px solid;` to `border: var(--fn-fg-on-dark) 2px solid;`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`.",
      "Changed `box-shadow: 0 0 0 1px var(--n000);` to `box-shadow: 0 0 0 1px var(--fn-fg-on-dark);`.",
      "Changed `background: white;` to `background: var(--fn-bg-surface);`.",
      "Changed `background-color: var(--n900);` to `background-color: rgba(var(--fn-shadow-rgb), 0.45);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-on-dark);`."
    ]
  },
  {
    "title": "MultiSelectDrawer",
    "path": "src/core/CustomDrawers/MultiSelectDrawer/MultiSelectDrawer.module.scss",
    "storyId": "customdrawers-multiselectdrawer-multiselectdrawer--default",
    "changes": [
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`."
    ]
  },
  {
    "title": "PhotoCarouselModal",
    "path": "src/core/CustomModals/PhotoCarouselModal/PhotoCarouselModal.module.scss",
    "storyId": "custommodals-photocarouselmodal-photocarouselmodal--default",
    "changes": [
      "Changed `background-color: var(--n700);` to `background-color: rgba(var(--fn-bg-dark-rgb), 0.7);`."
    ]
  },
  {
    "title": "DatePicker",
    "path": "src/core/DatePicker/DatePicker.module.scss",
    "storyId": "datepicker-datepicker--default",
    "changes": [
      "Changed `box-shadow: 0px 8px 24px 0px rgba(4, 5, 6, 0.08), 0px 4px 8px 0px rgba(4, 5, 6, 0.05),` to `box-shadow: 0px 8px 24px 0px rgba(var(--fn-shadow-rgb), 0.08), 0px 4px 8px 0px rgba(var(--fn-shadow-rgb), 0.05),`.",
      "Changed `0px 2px 2px 0px rgba(4, 5, 6, 0.03) !important;` to `0px 2px 2px 0px rgba(var(--fn-shadow-rgb), 0.03) !important;`.",
      "Changed `color: var(--n700);` to `color: var(--fn-fg);`."
    ]
  },
  {
    "title": "DateRangePicker",
    "path": "src/core/DateRangePicker/DateRangePicker.scss",
    "storyId": "daterangepicker-daterangepicker--default",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `box-shadow: 0px 12px 40px rgba(4, 5, 6, 0.08), 0px 8px 14px rgba(4, 5, 6, 0.05), 0px 4px 4px rgba(4, 5, 6, 0.03);` to `box-shadow: 0px 12px 40px rgba(var(--fn-shadow-rgb), 0.08), 0px 8px 14px rgba(var(--fn-shadow-rgb), 0.05), 0px 4px 4px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `color: #000000;` to `color: var(--fn-fg);`.",
      "Changed `background-color: rgb(255, 255, 255);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `border-color: transparent rgb(52, 73, 94) transparent transparent;` to `border-color: transparent var(--fn-fg-light) transparent transparent;`.",
      "Changed `border-color: transparent transparent transparent rgb(52, 73, 94);` to `border-color: transparent transparent transparent var(--fn-fg-light);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n300);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-cta-fg);`.",
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-bg-cta-fg);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`.",
      "Changed `background: rgba(255, 255, 255, 0.09);` to `background: rgba(var(--fn-bg-rgb), 0.09);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `background: #fff;` to `background: var(--fn-bg-surface);`."
    ]
  },
  {
    "title": "Divider",
    "path": "src/core/Divider/Divider.scss",
    "storyId": "divider-divider--default",
    "changes": [
      "Changed `border-bottom: 1px solid var(--n200);` to `border-bottom: 1px solid var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "DocumentDisplay",
    "path": "src/core/Documents/DocumentDisplay/DocumentDisplay.module.scss",
    "storyId": "documents-documentdisplay-documentdisplay--default",
    "changes": [
      "Changed `background-color: var(--n700);` to `background-color: rgba(var(--fn-bg-dark-rgb), 0.7);`."
    ]
  },
  {
    "title": "DocumentUpload",
    "path": "src/core/Documents/DocumentUpload/DocumentUpload.module.scss",
    "storyId": "documents-documentupload-documentupload--default",
    "changes": [
      "Changed `background: var(--n100);` to `background: var(--fn-bg-var);`.",
      "Changed `background: var(--n200);` to `background: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`."
    ]
  },
  {
    "title": "DragAndDropFile",
    "path": "src/core/DragAndDropFile/DragAndDropFile.module.scss",
    "storyId": "draganddropfile-draganddropfile--default",
    "changes": [
      "Changed `border: 2px dashed #ccc;` to `border: 2px dashed var(--fn-brd-gl);`.",
      "Changed `border-color: #007bff;` to `border-color: var(--i400);`.",
      "Changed `border-color: #007bff;` to `border-color: var(--i400);`."
    ]
  },
  {
    "title": "Drawer",
    "path": "src/core/Drawer/Drawer.module.scss",
    "storyId": "drawer-drawer--default",
    "changes": [
      "Changed `background-color: var(--drawer-header-bg, #fff); // fallback ensures header isn't transparent over content` to `background-color: var(--drawer-header-bg, var(--fn-bg-surface)); // fallback ensures header isn't transparent over content`."
    ]
  },
  {
    "title": "DropdownMenu",
    "path": "src/core/DropdownMenu/DropdownMenu.module.scss",
    "storyId": "dropdownmenu-dropdownmenu--default",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `filter: drop-shadow(0px 12px 40px rgba(4, 5, 6, 0.025)) drop-shadow(0px 8px 14px rgba(4, 5, 6, 0.05))` to `filter: drop-shadow(0px 12px 40px rgba(var(--fn-shadow-rgb), 0.025)) drop-shadow(0px 8px 14px rgba(var(--fn-shadow-rgb), 0.05))`.",
      "Changed `drop-shadow(0px 4px 4px rgba(4, 5, 6, 0.08));` to `drop-shadow(0px 4px 4px rgba(var(--fn-shadow-rgb), 0.08));`.",
      "Changed `border-color: var(--n000) transparent transparent transparent;` to `border-color: var(--fn-bg-surface) transparent transparent transparent;`.",
      "Changed `filter: drop-shadow(0px 4px 2px rgba(4, 5, 6, 0.1));` to `filter: drop-shadow(0px 4px 2px rgba(var(--fn-shadow-rgb), 0.1));`.",
      "Changed `border-color: var(--n000) transparent transparent transparent;` to `border-color: var(--fn-bg-surface) transparent transparent transparent;`.",
      "Changed `filter: drop-shadow(0px -2px 4px rgba(4, 5, 6, 0.05));` to `filter: drop-shadow(0px -2px 4px rgba(var(--fn-shadow-rgb), 0.05));`.",
      "Changed `border-color: transparent transparent var(--n000) transparent;` to `border-color: transparent transparent var(--fn-bg-surface) transparent;`.",
      "Changed `filter: drop-shadow(4px 0 2px rgba(4, 5, 6, 0.05));` to `filter: drop-shadow(4px 0 2px rgba(var(--fn-shadow-rgb), 0.05));`.",
      "Changed `border-color: transparent transparent transparent var(--n000);` to `border-color: transparent transparent transparent var(--fn-bg-surface);`.",
      "Changed `filter: drop-shadow(-4px 0px 2px rgba(4, 5, 6, 0.05));` to `filter: drop-shadow(-4px 0px 2px rgba(var(--fn-shadow-rgb), 0.05));`.",
      "Changed `border-color: transparent var(--n000) transparent transparent;` to `border-color: transparent var(--fn-bg-surface) transparent transparent;`."
    ]
  },
  {
    "title": "FadedCarousel",
    "path": "src/core/FadedCarousel/FadedCarousel.module.scss",
    "storyId": "fadedcarousel-fadedcarousel--default",
    "changes": [
      "Changed `background: linear-gradient(90deg, var(--n000) 50.33%, rgba(255, 255, 255, 0.00) 100%);` to `background: linear-gradient(90deg, var(--fn-bg) 50.33%, rgba(var(--fn-bg-rgb), 0) 100%);`.",
      "Changed `background: linear-gradient(90deg, rgba(255, 255, 255, 0.00) 0%, var(--n000) 50.6%);` to `background: linear-gradient(90deg, rgba(var(--fn-bg-rgb), 0) 0%, var(--fn-bg) 50.6%);`.",
      "Changed `background-color: var(--arrow-hover-color, rgba(4, 5, 6, 0.8)) !important;` to `background-color: var(--arrow-hover-color, rgba(var(--fn-shadow-rgb), 0.8)) !important;`.",
      "Changed `border: $x0_5 solid var(--n000) !important;` to `border: $x0_5 solid rgba(var(--fn-bg-rgb), 0.7) !important;`."
    ]
  },
  {
    "title": "FrostedGlass",
    "path": "src/core/FrostedGlass/FrostedGlass.module.scss",
    "storyId": "frostedglass-frostedglass--default",
    "changes": [
      "Changed `background-color: rgba(var(--n000-rgb), 0.3);` to `background-color: rgba(var(--fn-bg-rgb), 0.3);`."
    ]
  },
  {
    "title": "GalleryMediaItem",
    "path": "src/core/Gallery/Gallery/GalleryMediaItem/GalleryMediaItem.module.scss",
    "storyId": "gallery-gallery-gallerymediaitem-gallerymediaitem--image",
    "changes": [
      "Changed `background-color: rgba(var(--n900-rgb), .6);` to `background-color: rgba(var(--fn-shadow-rgb), 0.6);`.",
      "Changed `background-color: rgba(var(--n100-rgb), 0.2);` to `background-color: var(--fn-bg-hov-i-gl);`.",
      "Changed `background-color: rgba(var(--p500-rgb), .3);` to `background-color: rgba(var(--fn-bg-cta-rgb), 0.3);`.",
      "Changed `border-bottom: 1px solid var(--n000);` to `border-bottom: 1px solid rgba(var(--fn-bg-rgb), 0.3);`.",
      "Changed `background: linear-gradient(180deg, rgba(42, 53, 70, 0.00) 0%, #171D26 126.79%);` to `background: linear-gradient(180deg, rgba(var(--fn-fg-rgb), 0) 0%, var(--fn-bg-dark) 126.79%);`."
    ]
  },
  {
    "title": "PhotoPlaceholder",
    "path": "src/core/Gallery/Gallery/PhotoPlaceholder/PhotoPlaceholder.scss",
    "storyId": "gallery-gallery-gallery--default",
    "changes": [
      "Changed `background: var(--n100);` to `background: var(--fn-bg-var);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`."
    ]
  },
  {
    "title": "BlobAnimation",
    "path": "src/core/IllustrationBlob/BlobAnimation/BlobAnimation.module.scss",
    "storyId": "illustrationblob-blobanimation-blobanimation--blob-animation-story",
    "changes": [
      "Changed `--baseC: var(--p500);` to `--baseC: var(--fn-bg-cta);`."
    ]
  },
  {
    "title": "ImgWithLoader",
    "path": "src/core/ImgWithLoader/ImgWithLoader.module.scss",
    "storyId": "imgwithloader-imgwithloader--default",
    "changes": [
      "Changed `background: linear-gradient(180deg, rgba(42, 53, 70, 0.00) 21.79%, #171D26 126.79%);` to `background: linear-gradient(180deg, rgba(var(--fn-fg-rgb), 0) 21.79%, var(--fn-bg-dark) 126.79%);`."
    ]
  },
  {
    "title": "InfoBox",
    "path": "src/core/InfoBox/InfoBox.module.scss",
    "storyId": "infobox-infobox--default",
    "changes": [
      "Changed `border-color: var(--p100);` to `border-color: var(--i100);`."
    ]
  },
  {
    "title": "LineAlert",
    "path": "src/core/LineAlert/LineAlert.module.scss",
    "storyId": "linealert-linealert--default",
    "changes": [
      "Changed `-webkit-box-shadow: 13px 5px 19px 5px rgba(0, 0, 0, 0.13);` to `-webkit-box-shadow: 13px 5px 19px 5px rgba(var(--fn-shadow-rgb), 0.13);`.",
      "Changed `box-shadow: 13px 5px 19px 5px rgba(0, 0, 0, 0.13);` to `box-shadow: 13px 5px 19px 5px rgba(var(--fn-shadow-rgb), 0.13);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`."
    ]
  },
  {
    "title": "Link",
    "path": "src/core/Link/Link.module.scss",
    "storyId": "link-link--default",
    "changes": [
      "Changed `color: var(--n300);` to `color: var(--fn-fg-lightest);`."
    ]
  },
  {
    "title": "ListItem",
    "path": "src/core/ListItem/ListItem.module.scss",
    "changes": [
      "Changed `border: $x0_25 solid var(--p500);` to `border: $x0_25 solid var(--i400);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `box-shadow: 0px 2px 4px -1px rgba(29, 29, 32, 0.16), 0px 4px 5px rgba(29, 29, 32, 0.05), 0px 1px 10px rgba(29, 29, 32, 0.08);` to `box-shadow: 0px 2px 4px -1px rgba(var(--fn-shadow-rgb), 0.16), 0px 4px 5px rgba(var(--fn-shadow-rgb), 0.05), 0px 1px 10px rgba(var(--fn-shadow-rgb), 0.08);`."
    ]
  },
  {
    "title": "ListItem",
    "path": "src/core/ListItems/ListItem/ListItem.module.scss",
    "changes": [
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n200);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`."
    ]
  },
  {
    "title": "ListLoader",
    "path": "src/core/ListLoader/ListLoader.scss",
    "changes": [
      "Changed `background: #fff;` to `background: var(--fn-bg-surface);`.",
      "Changed `border-color: #e5e6e9;` to `border-color: var(--fn-divider-gl);`.",
      "Changed `to {background-color:#f6f7f8;transition: all 0.3s ease-out;}` to `to {background-color:var(--fn-bg-var);transition: all 0.3s ease-out;}`.",
      "Changed `background-color: #CCC;` to `background-color: var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "Loader",
    "path": "src/core/Loader/Loader.scss",
    "storyId": "loader-loader--loading",
    "changes": [
      "Changed `background-color: rgba(16, 16, 16, 0.5);` to `background-color: rgba(var(--fn-shadow-rgb), 0.5);`.",
      "Changed `box-shadow: 0 6px 0 0 #ffffff;` to `box-shadow: 0 6px 0 0 var(--fn-fg-on-dark);`."
    ]
  },
  {
    "title": "Modal",
    "path": "src/core/Modal/Modal.scss",
    "storyId": "modal-modal--modal-story",
    "changes": [
      "Changed `--shadow-small: 0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06);` to `--shadow-small: 0 1px 3px 0 rgba(var(--fn-shadow-rgb), 0.1), 0 1px 2px 0 rgba(var(--fn-shadow-rgb), 0.06);`.",
      "Changed `--shadow-medium: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);` to `--shadow-medium: 0 4px 6px -1px rgba(var(--fn-shadow-rgb), 0.1), 0 2px 4px -1px rgba(var(--fn-shadow-rgb), 0.06);`.",
      "Changed `--shadow-large: 0px 12px 40px rgba(4, 5, 6, 0.0239911), 0px 8px 14px rgba(4, 5, 6, 0.05), 0px 4px 4px rgba(4, 5, 6, 0.08);` to `--shadow-large: 0px 12px 40px rgba(var(--fn-shadow-rgb), 0.0239911), 0px 8px 14px rgba(var(--fn-shadow-rgb), 0.05), 0px 4px 4px rgba(var(--fn-shadow-rgb), 0.08);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`."
    ]
  },
  {
    "title": "ModalFooter",
    "path": "src/core/Modal/ModalFooter/ModalFooter.scss",
    "storyId": "modal-modal--modal-story",
    "changes": [
      "Changed `border-top: 1px solid var(--n200);` to `border-top: 1px solid var(--fn-divider-gl);`.",
      "Changed `box-shadow: inset 0 1px 0 #e6e9f0;` to `box-shadow: inset 0 1px 0 var(--fn-divider-gl);`.",
      "Changed `background-color: rgba(var(--n000-rgb), 0.8);` to `background-color: rgba(var(--fn-bg-rgb), 0.8);`."
    ]
  },
  {
    "title": "ModalRoot",
    "path": "src/core/Modal/ModalRoot/ModalRoot.scss",
    "storyId": "modal-modal--modal-story",
    "changes": [
      "Changed `background-color: rgba(var(--n900-rgb), 0.4);` to `background-color: rgba(var(--fn-shadow-rgb), 0.4);`."
    ]
  },
  {
    "title": "ModalSplitView",
    "path": "src/core/Modal/ModalSplitView/ModalSplitView.scss",
    "storyId": "modal-modalsplitview-modalsplitview--left-priority",
    "changes": [
      "Changed `box-shadow: 8px 0 24px rgba(4, 5, 6, 0.08), 4px 0 8px rgba(4, 5, 6, 0.05), 2px 0 2px rgba(4, 5, 6, 0.03);` to `box-shadow: 8px 0 24px rgba(var(--fn-shadow-rgb), 0.08), 4px 0 8px rgba(var(--fn-shadow-rgb), 0.05), 2px 0 2px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `background-color: rgba(var(--n000-rgb), 0.8);` to `background-color: rgba(var(--fn-bg-rgb), 0.8);`.",
      "Added `&--overlay {`.",
      "Added `z-index: 4;`.",
      "Added `box-shadow: -8px 0 24px rgba(var(--fn-shadow-rgb), 0.08), -4px 0 8px rgba(var(--fn-shadow-rgb), 0.05), -2px 0 2px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Added `&--with-bottom-margin {`.",
      "Added `border-bottom-left-radius: 8px;`.",
      "Added `border-bottom-right-radius: 8px;`."
    ]
  },
  {
    "title": "ModalStepperStep",
    "path": "src/core/Modal/ModalStepper/ModalStepperSteps/ModalStepperStep/ModalStepperStep.module.scss",
    "storyId": "modal-modalstepper-modalstepper--modal-stepper-story",
    "changes": [
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`."
    ]
  },
  {
    "title": "ContentPlaceholder",
    "path": "src/core/Notification/ContentPlaceholder/ContentPlaceholder.scss",
    "changes": [
      "Changed `background: #C9C3F3;` to `background: var(--a1100);`.",
      "Changed `border: 1px dashed #3C28CC;` to `border: 1px dashed var(--a1500);`."
    ]
  },
  {
    "title": "NotificationAction",
    "path": "src/core/Notification/NotificationAction/NotificationAction.scss",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `box-shadow: inset 0 1px 0 #E6E9F0;` to `box-shadow: inset 0 1px 0 var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "QuouteContainer",
    "path": "src/core/Notification/QuoteContainer/QuouteContainer.scss",
    "changes": [
      "Changed `background: var(--n100);` to `background: var(--fn-bg-var);`."
    ]
  },
  {
    "title": "NotificationAction",
    "path": "src/core/NotificationAction/NotificationAction.scss",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `box-shadow: inset 0 1px 0 #E6E9F0;` to `box-shadow: inset 0 1px 0 var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "PopoverPopper",
    "path": "src/core/Popover/PopoverPopper/PopoverPopper.scss",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `border-color: var(--n000) transparent transparent transparent;` to `border-color: var(--fn-bg-surface) transparent transparent transparent;`.",
      "Changed `filter: drop-shadow(0px 4px 2px rgba(4, 5, 6, 0.1));` to `filter: drop-shadow(0px 4px 2px rgba(var(--fn-shadow-rgb), 0.1));`.",
      "Changed `border-color: var(--n000) transparent transparent transparent;` to `border-color: var(--fn-bg-surface) transparent transparent transparent;`.",
      "Changed `filter: drop-shadow(0px -4px 2px rgba(4, 5, 6, 0.1));` to `filter: drop-shadow(0px -4px 2px rgba(var(--fn-shadow-rgb), 0.1));`.",
      "Changed `border-color: transparent transparent var(--n000) transparent;` to `border-color: transparent transparent var(--fn-bg-surface) transparent;`.",
      "Changed `filter: drop-shadow(4px 0 2px rgba(4, 5, 6, 0.1));` to `filter: drop-shadow(4px 0 2px rgba(var(--fn-shadow-rgb), 0.1));`.",
      "Changed `border-color: transparent transparent transparent var(--n000);` to `border-color: transparent transparent transparent var(--fn-bg-surface);`.",
      "Changed `filter: drop-shadow(-4px 0px 2px rgba(4, 5, 6, 0.1));` to `filter: drop-shadow(-4px 0px 2px rgba(var(--fn-shadow-rgb), 0.1));`.",
      "Changed `border-color: transparent var(--n000) transparent transparent;` to `border-color: transparent var(--fn-bg-surface) transparent transparent;`.",
      "Changed `background: var(--n800);` to `background: var(--fn-bg-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `border-color: var(--n800) transparent transparent transparent;` to `border-color: var(--fn-bg-dark) transparent transparent transparent;`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `border-color: var(--n800) transparent transparent transparent;` to `border-color: var(--fn-bg-dark) transparent transparent transparent;`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `border-color: transparent transparent var(--n800) transparent;` to `border-color: transparent transparent var(--fn-bg-dark) transparent;`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `border-color: transparent transparent transparent var(--n800);` to `border-color: transparent transparent transparent var(--fn-bg-dark);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `border-color: transparent var(--n800) transparent transparent;` to `border-color: transparent var(--fn-bg-dark) transparent transparent;`."
    ]
  },
  {
    "title": "QuoteContainer",
    "path": "src/core/QuoteContainer/QuoteContainer.module.scss",
    "changes": [
      "Changed `fill: rgba(var(--n500-rgb),0.5); // Use the accent color for the quote marks` to `fill: rgba(var(--fn-fg-light-rgb),0.5); // Use the accent color for the quote marks`."
    ]
  },
  {
    "title": "RadioButton",
    "path": "src/core/RadioButton/RadioButton.scss",
    "storyId": "radiobutton-radiobutton--default",
    "changes": [
      "Changed `border: $x0_25 solid var(--n400);` to `border: $x0_25 solid var(--fn-brd-gl);`.",
      "Changed `border: $x0_5 + $x0_125 solid var(--n500);` to `border: $x0_5 + $x0_125 solid var(--fn-brd-gl);`.",
      "Changed `border: $x0_5+$x0_125 solid var(--p500);` to `border: $x0_5+$x0_125 solid var(--fn-bg-cta);`.",
      "Changed `border: $x0_5+$x0_125 solid var(--p700);` to `border: $x0_5+$x0_125 solid var(--fn-bg-cta-hov);`.",
      "Changed `border: $x0_5+$x0_125 solid var(--n100);` to `border: $x0_5+$x0_125 solid var(--fn-brd-gl);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `border: $x0_125 solid var(--n400);` to `border: $x0_125 solid var(--fn-brd-gl);`.",
      "Changed `border: $x0_125 solid var(--n400);` to `border: $x0_125 solid var(--fn-brd-gl);`."
    ]
  },
  {
    "title": "LexicalJumpReset",
    "path": "src/core/RichTextEditor/LexicalTheme/LexicalJumpReset.scss",
    "storyId": "richtexteditor-richtexteditor--rich-text-editor-story",
    "changes": [
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`.",
      "Changed `color: var(--p700);` to `color: var(--fn-fg-cta-hov);`."
    ]
  },
  {
    "title": "LexicalTheme",
    "path": "src/core/RichTextEditor/LexicalTheme/LexicalTheme.module.scss",
    "storyId": "richtexteditor-richtexteditor--rich-text-editor-story",
    "changes": [
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`."
    ]
  },
  {
    "title": "RichTextEditor",
    "path": "src/core/RichTextEditor/RichTextEditor.module.scss",
    "storyId": "richtexteditor-richtexteditor--rich-text-editor-story",
    "changes": [
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `border-color: var(--p500);` to `border-color: var(--fn-fg-cta);`.",
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `border-color: var(--p400);` to `border-color: var(--fn-bg-cta);`.",
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `background: var(--n200);` to `background: var(--fn-bg-disabled);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-disabled);`.",
      "Changed `color: var(--n400);` to `color: var(--fn-fg-lightest);`."
    ]
  },
  {
    "title": "RteLinkEditor",
    "path": "src/core/RichTextEditor/RteLinkEditor/RteLinkEditor.module.scss",
    "storyId": "richtexteditor-richtexteditor--rich-text-editor-story",
    "changes": [
      "Changed `background: var(--functional-bg-surface, #fff);` to `background: var(--fn-bg-surface);`.",
      "Changed `border: 1px solid var(--ai, rgba(131, 119, 228, 0.25));` to `border: 1px solid var(--ai, rgba(var(--a1300-rgb), 0.25));`.",
      "Changed `box-shadow: 0px 16px 64px 0px rgba(4, 5, 6, 0.08), 0px 12px 20px 0px rgba(4, 5, 6, 0.05),` to `box-shadow: 0px 16px 64px 0px rgba(var(--fn-shadow-rgb), 0.08), 0px 12px 20px 0px rgba(var(--fn-shadow-rgb), 0.05),`.",
      "Changed `0px 6px 8px 0px rgba(4, 5, 6, 0.03);` to `0px 6px 8px 0px rgba(var(--fn-shadow-rgb), 0.03);`.",
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`.",
      "Changed `color: var(--p700);` to `color: var(--fn-fg-cta-hov);`."
    ]
  },
  {
    "title": "RteToolbar",
    "path": "src/core/RichTextEditor/RteToolbar/RteToolbar.module.scss",
    "storyId": "richtexteditor-richtexteditor--rich-text-editor-story",
    "changes": [
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `color: var(--n200);` to `color: var(--fn-fg-lightest);`.",
      "Changed `background: var(--n200);` to `background: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "SearchableSelect",
    "path": "src/core/SearchableSelect/SearchableSelect.scss",
    "storyId": "searchableselect-searchableselect--default",
    "changes": [
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`.",
      "Changed `background: var(--n300);` to `background: rgba(var(--fn-bg-dark-rgb), 0.3);`.",
      "Changed `border-top: 1px solid var(--n200);` to `border-top: 1px solid var(--fn-divider-gl);`.",
      "Changed `background: #FFFFFF;` to `background: var(--fn-bg-surface);`.",
      "Changed `color: var(--n700);` to `color: var(--fn-fg);`.",
      "Changed `background: #FFFFFF;` to `background: var(--fn-bg-surface);`.",
      "Changed `background: var(--n100);` to `background: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`."
    ]
  },
  {
    "title": "SegmentBar",
    "path": "src/core/SegmentBar/SegmentBar.module.scss",
    "changes": [
      "Added `.bar {`.",
      "Added `display: flex;`.",
      "Added `width: 100%;`.",
      "Added `gap: 1px;`.",
      "Added `overflow: hidden;`.",
      "Added `border-radius: 999px;`.",
      "Added `.segment {`.",
      "Added `flex-basis: 0;`.",
      "Added `min-width: 0;`.",
      "Added `transition: flex-grow 0.5s cubic-bezier(0.23, 1, 0.32, 1), background 0.25s ease;`."
    ]
  },
  {
    "title": "Select",
    "path": "src/core/Select/Select.module.scss",
    "storyId": "select-select--select-story",
    "changes": [
      "Changed `background-color: var(--n000) !important;` to `background-color: var(--fn-bg) !important;`."
    ]
  },
  {
    "title": "Arrow",
    "path": "src/core/SlideCarousel/Arrow/Arrow.module.scss",
    "storyId": "slidecarousel-slidecarousel--slide-carousel-with-arrows",
    "changes": [
      "Changed `background: rgba(var(--n000-rgb), 0.5);` to `background: rgba(var(--fn-bg-rgb), 0.5);`.",
      "Changed `color: var(--n700);` to `color: var(--fn-fg);`.",
      "Changed `background: rgba(var(--n000-rgb), 0.7);` to `background: rgba(var(--fn-bg-rgb), 0.7);`."
    ]
  },
  {
    "title": "Bullet",
    "path": "src/core/SlideCarousel/Bullet/Bullet.module.scss",
    "storyId": "slidecarousel-slidecarousel--slide-carousel-with-bullets",
    "changes": [
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`."
    ]
  },
  {
    "title": "Slider",
    "path": "src/core/Slider/Slider.scss",
    "storyId": "slider-slider--default",
    "changes": [
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`.",
      "Changed `background-color: var(--p600);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--p700);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--p500); // @todo Had to use inline SVG, because Webpack is serving wrong urls` to `background-color: var(--fn-bg-cta); // @todo Had to use inline SVG, because Webpack is serving wrong urls`.",
      "Changed `box-shadow: 0 8px 24px rgba(4, 5, 6, 0.03), 0 4px 8px rgba(4, 5, 6, 0.05), 0 2px 2px rgba(4, 5, 6, 0.08);` to `box-shadow: 0 8px 24px rgba(var(--fn-shadow-rgb), 0.03), 0 4px 8px rgba(var(--fn-shadow-rgb), 0.05), 0 2px 2px rgba(var(--fn-shadow-rgb), 0.08);`.",
      "Changed `background-color: var(--p700);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--p700);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--p700);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-divider-gl);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `color: var(--n700);` to `color: var(--fn-fg);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`.",
      "Changed `border: 2px solid var(--n300);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `border: 2px solid var(--n400);` to `border: 2px solid var(--fn-brd-gl);`.",
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background-color: var(--p500);` to `background-color: var(--fn-bg-cta);`.",
      "Changed `background-color: var(--p600);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background-color: var(--p600);` to `background-color: var(--fn-bg-cta-hov);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg-surface);`.",
      "Changed `filter: drop-shadow(4px 0px 2px rgba(4, 5, 6, 0.15));` to `filter: drop-shadow(4px 0px 2px rgba(var(--fn-shadow-rgb), 0.15));`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg-surface);`."
    ]
  },
  {
    "title": "AcceptModal",
    "path": "src/core/StandardModals/AcceptModal/AcceptModal.scss",
    "changes": [
      "Changed `box-shadow: inset 0 $x0_125 0 var(--n200);` to `box-shadow: inset 0 $x0_125 0 var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "ConfirmModal",
    "path": "src/core/StandardModals/ConfirmModal/ConfirmModal.scss",
    "changes": [
      "Changed `box-shadow: inset 0 $x0_125 0 var(--n200);` to `box-shadow: inset 0 $x0_125 0 var(--fn-divider-gl);`."
    ]
  },
  {
    "title": "StatusBadge",
    "path": "src/core/StatusBadge/StatusBadge.module.scss",
    "storyId": "statusbadge-statusbadge--status-badge-info",
    "changes": [
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`."
    ]
  },
  {
    "title": "Switch",
    "path": "src/core/Switch/Switch.scss",
    "changes": [
      "Changed `border: 1px solid var(--n300);` to `border: 1px solid var(--fn-brd-gl);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`.",
      "Changed `border: 1px solid var(--p500);` to `border: 1px solid var(--fn-bg-cta);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg);`.",
      "Changed `box-shadow: 0px -2px 4px rgba(4, 5, 6, 0.05), 0px 8px 16px rgba(4, 5, 6, 0.1), 0px 4px 8px rgba(4, 5, 6, 0.1), 0px 2px 4px rgba(4, 5, 6, 0.15);` to `box-shadow: 0px -2px 4px rgba(var(--fn-shadow-rgb), 0.05), 0px 8px 16px rgba(var(--fn-shadow-rgb), 0.1), 0px 4px 8px rgba(var(--fn-shadow-rgb), 0.1), 0px 2px 4px rgba(var(--fn-shadow-rgb), 0.15);`.",
      "Changed `box-shadow: -1px 0 0 6px rgba(4, 5, 6, 0.1);` to `box-shadow: -1px 0 0 6px rgba(var(--fn-shadow-rgb), 0.1);`.",
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`.",
      "Changed `box-shadow: 0px -2px 4px rgba(0, 98, 255, 0.1), 0px 8px 16px rgba(0, 98, 255, 0.2), 0px 4px 8px rgba(0, 98, 255, 0.2), 0px 2px 4px rgba(0, 98, 255, 0.25);` to `box-shadow: 0px -2px 4px rgba(var(--fn-bg-cta-rgb), 0.1), 0px 8px 16px rgba(var(--fn-bg-cta-rgb), 0.2), 0px 4px 8px rgba(var(--fn-bg-cta-rgb), 0.2), 0px 2px 4px rgba(var(--fn-bg-cta-rgb), 0.25);`.",
      "Changed `box-shadow: 1px 0 0 6px rgba(0, 98, 255, 0.2);` to `box-shadow: 1px 0 0 6px rgba(var(--fn-bg-cta-rgb), 0.2);`."
    ]
  },
  {
    "title": "TableCell",
    "path": "src/core/Table/TableCell/TableCell.module.scss",
    "storyId": "table-table--default",
    "changes": [
      "Changed `border-bottom: 1px solid var(--n200);` to `border-bottom: 1px solid var(--fn-divider-gl);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background: linear-gradient(to right, rgba(var(--n400-rgb), 0.45) 0, rgba(var(--n400-rgb), 0.30) 0, rgba(var(--n400-rgb), 0.12) $x0_25, rgba(var(--n400-rgb), 0) 100%);` to `background: linear-gradient(to right, rgba(var(--fn-shadow-rgb), 0.225) 0, rgba(var(--fn-shadow-rgb), 0.15) 0, rgba(var(--fn-shadow-rgb), 0.06) $x0_25, rgba(var(--fn-shadow-rgb), 0) 100%);`."
    ]
  },
  {
    "title": "FooterPagination",
    "path": "src/core/Table/TableFooter/FooterPagination/FooterPagination.module.scss",
    "storyId": "table-table--default",
    "changes": [
      "Changed `color: var(--n300)!important;` to `color: var(--fn-fg-lightest)!important;`."
    ]
  },
  {
    "title": "FooterShowMore",
    "path": "src/core/Table/TableFooter/FooterShowMore/FooterShowMore.module.scss",
    "storyId": "table-table--default",
    "changes": [
      "Changed `color: var(--n300)!important;` to `color: var(--fn-fg-lightest)!important;`."
    ]
  },
  {
    "title": "TableFooter",
    "path": "src/core/Table/TableFooter/TableFooter.module.scss",
    "storyId": "table-table--default",
    "changes": [
      "Changed `color: var(--n300)!important;` to `color: var(--fn-fg-lightest)!important;`."
    ]
  },
  {
    "title": "TableHeader",
    "path": "src/core/Table/TableHeader/TableHeader.module.scss",
    "storyId": "table-table--default",
    "changes": [
      "Changed `border-bottom: 2px solid var(--n200);` to `border-bottom: 2px solid var(--fn-divider-gl);`.",
      "Changed `background: var(--n100);` to `background: var(--fn-bg-var);`.",
      "Changed `background: linear-gradient(to right, rgba(var(--n400-rgb), 0.45) 0, rgba(var(--n400-rgb), 0.30) 0, rgba(var(--n400-rgb), 0.12) $x0_25, rgba(var(--n400-rgb), 0) 100%);` to `background: linear-gradient(to right, rgba(var(--fn-shadow-rgb), 0.225) 0, rgba(var(--fn-shadow-rgb), 0.15) 0, rgba(var(--fn-shadow-rgb), 0.06) $x0_25, rgba(var(--fn-shadow-rgb), 0) 100%);`."
    ]
  },
  {
    "title": "Tab",
    "path": "src/core/Tabs/Tab/Tab.module.scss",
    "storyId": "tabs-tab-tab--basic-tabs",
    "changes": [
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `background-color: var(--p100);` to `background-color: var(--i100);`.",
      "Changed `border-bottom: 2px solid var(--n200);` to `border-bottom: 2px solid var(--fn-divider-gl);`.",
      "Changed `border-color: var(--p500);` to `border-color: var(--i400);`."
    ]
  },
  {
    "title": "TabsCustomScroll",
    "path": "src/core/Tabs/TabsCustomScroll/TabsCustomScroll.module.scss",
    "storyId": "tabs-tabscustomscroll-tabscustomscroll--default",
    "changes": [
      "Changed `box-shadow: -$x0_25 0 $x0_25 rgba(4, 5, 6, 0.03), -$x0_5 0 $x1 rgba(4, 5, 6, 0.05), -$x1 0 $x3 rgba(4, 5, 6, 0.08);` to `box-shadow: -$x0_25 0 $x0_25 rgba(var(--fn-shadow-rgb), 0.03), -$x0_5 0 $x1 rgba(var(--fn-shadow-rgb), 0.05), -$x1 0 $x3 rgba(var(--fn-shadow-rgb), 0.08);`.",
      "Changed `border: $x0_5 solid var(--n000);` to `border: $x0_5 solid var(--fn-bg);`.",
      "Changed `background-color: var(--n100);` to `background-color: var(--fn-bg-var);`.",
      "Changed `background-color: var(--n200);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`.",
      "Changed `fill: var(--n500);` to `fill: var(--fn-fg-light);`.",
      "Changed `background-color: var(--n300);` to `background-color: var(--fn-bg-hov-n-gl);`."
    ]
  },
  {
    "title": "Tag",
    "path": "src/core/TagList/Tag/Tag.scss",
    "storyId": "taglist-taglist--default",
    "changes": [
      "Changed `background-color: var(--n000);` to `background-color: var(--fn-bg);`.",
      "Changed `background-color: var(--n500);` to `background-color: var(--fn-bg-hov-n-gl);`.",
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `fill: var(--n000);` to `fill: var(--fn-fg-on-dark);`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `fill: var(--n500);` to `fill: var(--fn-fg-light);`.",
      "Changed `background: #FFFFFF;` to `background: var(--fn-bg-surface);`."
    ]
  },
  {
    "title": "Text",
    "path": "src/core/Text/Text.scss",
    "storyId": "text-stories-text--text-standard",
    "changes": [
      "Changed `background: rgba(255, 0, 0, 0.2);` to `background: rgba(var(--e500-rgb), 0.2);`.",
      "Changed `text-shadow: 0 0 12px var(--n500);` to `text-shadow: 0 0 12px var(--fn-fg-light);`.",
      "Changed `background: rgba(0, 255, 0, 0.2);` to `background: rgba(var(--s400-rgb), 0.2);`.",
      "Changed `background: rgba(0, 0, 255, 0.2);` to `background: rgba(var(--fn-bg-cta-rgb), 0.2);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-bg);`."
    ]
  },
  {
    "title": "TogglerWithText",
    "path": "src/core/TogglerWithText/TogglerWithText.module.scss",
    "changes": [
      "Changed `background-color: var(--n200);` to `background-color: var(--fn-bg-var);`."
    ]
  },
  {
    "title": "TrendIndicator",
    "path": "src/core/TrendIndicator/TrendIndicator.module.scss",
    "changes": [
      "Added `.indicator {`.",
      "Added `display: inline-flex;`.",
      "Added `flex-shrink: 0;`.",
      "Added `align-items: center;`.",
      "Added `.delta {`.",
      "Added `display: inline-flex;`.",
      "Added `flex-shrink: 0;`.",
      "Added `align-items: center;`.",
      "Added `gap: 2px;`.",
      "Added `.delta-value {`.",
      "Added `font-size: 12px;`.",
      "Added `font-weight: 500;`.",
      "Added `line-height: 1;`.",
      "Added `font-variant-numeric: tabular-nums;`."
    ]
  },
  {
    "title": "VideoPlayer.theme",
    "path": "src/core/VideoPlayer/VideoPlayer.theme.scss",
    "storyId": "videoplayer-videoplayer--default",
    "changes": [
      "Changed `color: var(--n000);` to `color: var(--fn-fg-on-dark);`.",
      "Changed `background: var(--n000);` to `background: var(--fn-fg-on-dark);`.",
      "Changed `background-color: rgba(var(--p300-rgb), 0.75);` to `background-color: rgba(var(--i400-rgb), 0.75);`."
    ]
  },
  {
    "title": "InputBase",
    "path": "src/core/_internal/InputBase/InputBase.scss",
    "storyId": "internal-inputbase-stories-inputbase--id-test",
    "changes": [
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `background: var(--white);` to `background: var(--fn-bg);`.",
      "Changed `color: var(--p500);` to `color: var(--fn-fg-cta);`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`.",
      "Changed `color: var(--n400);` to `color: var(--fn-fg-lightest);`.",
      "Changed `color: var(--n700);` to `color: var(--fn-fg);`.",
      "Changed `background: var(--white);` to `background: var(--fn-bg);`.",
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `border-color: var(--p500);` to `border-color: var(--fn-fg-cta);`.",
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `border-color: var(--p400);` to `border-color: var(--fn-bg-cta);`.",
      "Changed `border-color: var(--n300);` to `border-color: var(--fn-brd-gl);`.",
      "Changed `background: var(--n200);` to `background: var(--fn-bg-disabled);`.",
      "Changed `background-color: var(--p100);` to `background-color: var(--i100);`.",
      "Changed `color: var(--n400) !important;` to `color: var(--fn-fg-lightest) !important;`.",
      "Changed `color: var(--n500);` to `color: var(--fn-fg-light);`."
    ]
  },
  {
    "title": "_material-ripple",
    "path": "src/styles/_material-ripple.scss",
    "changes": [
      "Changed `background: #bdc3c7;` to `background: rgba(var(--fn-shadow-rgb), 0.25);`."
    ]
  },
  {
    "title": "_mixins",
    "path": "src/styles/_mixins.scss",
    "changes": [
      "Changed `background-color: var(--n100);` to `background-color: rgba(var(--fn-bg-hov-n-gl-rgb), 0.15);`."
    ]
  }
];
